selected_columns = {
    "PUWG 1992 X": "PUWG 1992 X",
    "PUWG 1992 Y": "PUWG 1992 Y",
    "Data poboru próbki": "date",
    "Rok badań": "year",
    "Numer punktu pomiarowego wg MONBADA": "id",
    "Rodzaj punktu pomiarowego": "Type of Measurement Point",
    "Głębokość do stropu warstwy wodonośnej [m p.p.t.]": "Depth to Top of Aquifer Layer [m b.g.l.]",
    "Przedział ujętej warstwy wodonośnej [m p.p.t.]": "Range of Captured Aquifer Layer [m b.g.l.]",
    "Bifentryna [mg/l]": "Bifenthrin [mg/l]",
    "Flonikamid (IKI-220) [mg/l]": "Flonicamid (IKI-220) [mg/l]",
    "Flufenacet [mg/l]": "Flufenacet [mg/l]",
    "Fluopyram [mg/l]": "Fluopyram [mg/l]",
    "Trifloksystrobina [mg/l]": "Trifloxystrobin [mg/l]",
    "PFOS [mg/l]": "PFOS [mg/l]",
    "Nowaluron [mg/l]": "Novaluron [mg/l]",
    "Przewodność elektrolityczna właściwa w 20°C - wartość terenowa [µS/cm]": "EC [µS/cm]",
    "Odczyn pH - wartość laboratoryjna": "pH ",
    "Arsen [mgAs/l]": "Arsenic [mgAs/l]",
    "Chlorki [mgCl/l]": "Chlorides [mgCl/l]",
    "Cynk [mgZn/l]": "Zinc [mgZn/l]",
    "Kadm [mgCd/l]": "Cadmium [mgCd/l]",
    "Magnez [mgMg/l]": "Magnesium [mgMg/l]",
    "Ołów [mgPb/l]": "Lead [mgPb/l]",
    "Potas [mgK/l]": "Potassium [mgK/l]",
    "Sód [mgNa/l]": "Sodium [mgNa/l]",
    "Wapń [mgCa/l]": "Calcium [mgCa/l]",
    "Fosforany[mgPO4 / l]": "Phosphates [mgPO4/l]"
}

