# list of parameters in the parameter column
PARAMETER_VALUES = [
    'HOLDING',
    'UAA',
    'SO_EURO',
    'HoldingsPerKm2',
    'UAA',
    'ARA',
    'AraShare',
    'PECR',
    'PecrShare',
    'J0000T',
    'GrassShare',
    'Q0000T',
    'FallowShare',
    'F4000T',
    'W1000T',
    'O1000T',
    'LSU',
    'LSUdensity',
    'BOVINE',
    'BovineDensity',
    'PIGS',
    'PigsDensity',
    'SHEEP',
    'SheepDensity',
    'GOATS',
    'GoatsDensity',
    'POULTRY',
    'PoultryDensity',
    'FAM_FARM',
    'FLF_D_R_T_PERS',
    'FLF_D_RFAM_T_PERS',
    'FLF_D_RNFAM_T_PERS',
    'AWU',
    'AWU_FAM',
    'AWU_NFAM',
    'AWU_WORKER',
    'HOLDING',
    'Y_LT40',
    'Y_LT40_Share',
    'Y_GE65',
    'Y_GE65_Share',
    'AGE_MANAGER',
    'AGE',
    'HOLDING',
    'BASIC',
    'BasicShare',
    'FULL',
    'FullShare',
    'PRACT',
    'PractShare',
    'Control',
    'FEMALE',
    'MALE',
    'FemShare',
    'HOLDING',
    'UAAXK0000_ORG',
    'OrgShare',
    'UAA_IB',
    'IrrShare'
]

# selection list for parameters
PARAMETER_SELECTION = []

# aliases for the data fields
DATA_ALIASES = {
    'UAA': 'land cover',
    'ARA': 'land cover',
    'AraShare': 'land cover',
    'PECR': 'land cover',
    'PecrShare': 'land cover',
    'J0000T': 'land cover',
    'GrassShare': 'land cover',
    'Q0000T': 'land cover',
    'FallowShare': 'land cover',
    'F4000T': 'land cover',
    'W1000T': 'land cover',
    'O1000T': 'land cover',
    'UAAXK0000_ORG': 'land cover',
    'OrgShare': 'land cover',
    'HOLDING': 'agricultural structure',
    'UAA': 'agricultural structure',
    'SO_EURO': 'agricultural structure',
    'HoldingsPerKm2': 'agricultural structure',
    'LSU': 'livestock pressure',
    'LSUdensity': 'livestock pressure',
    'BOVINE': 'livestock pressure',
    'BovineDensity': 'livestock pressure',
    'PIGS': 'livestock pressure',
    'PigsDensity': 'livestock pressure',
    'SHEEP': 'livestock pressure',
    'SheepDensity': 'livestock pressure',
    'GOATS': 'livestock pressure',
    'GoatsDensity': 'livestock pressure',
    'POULTRY': 'livestock pressure',
    'PoultryDensity': 'livestock pressure',
    'UAA_IB': 'surface water quantity', 
    'IrrShare': 'surface water quantity'
 }


# global mapping of parameter codes to descriptions and units
GLOBAL_MAPPING = {}