# list of parameters in the parameter column
PARAMETER_VALUES = [
    'HOLDING',
    'UAA',
    'SO_EURO',
    'HoldingsPerKm2',
    'UAA',
    'ARA',
    'AraShare',
    'PECR',
    'PecrShare',
    'J0000T',
    'GrassShare',
    'Q0000T',
    'FallowShare',
    'F4000T',
    'W1000T',
    'O1000T',
    'LSU',
    'LSUdensity',
    'BOVINE',
    'PIGS',
    'SHEEP',
    'GOATS',
    'POULTRY',
    'FAM_FARM',
    'FLF_D_R_T_PERS',
    'FLF_D_RFAM_T_PERS',
    'FLF_D_RNFAM_T_PERS',
    'AWU',
    'AWU_FAM',
    'AWU_NFAM',
    'AWU_WORKER',
    'HOLDING',
    'Y_LT40',
    'Y_LT40_Share',
    'Y_GE65',
    'Y_GE65_Share',
    'AGE_MANAGER',
    'AGE',
    'HOLDING',
    'BASIC',
    'BasicShare',
    'FULL',
    'FullShare',
    'PRACT',
    'PractShare',
    'Control',
    'FEMALE',
    'MALE',
    'FemShare',
    'HOLDING',
    'UAAXK0000_ORG',
    'OrgShare',
    'UAA_IB',
    'IrrShare'
]

# selection list for parameters
PARAMETER_SELECTION = []

# aliases for the data fields
DATA_ALIASES = {
    'UAA': 'land cover',
    'ARA': 'land cover',
    'AraShare': 'land cover',
    'PECR': 'land cover',
    'PecrShare': 'land cover',
    'J0000T': 'land cover',
    'GrassShare': 'land cover',
    'Q0000T': 'land cover',
    'FllwShr': 'land cover',
    'UAAXK00': 'land cover',
    'OrgShar': 'land cover',
    'HOLDING': 'agricultural structure',
    'UAA': 'agricultural structure',
    'SO_EURO': 'agricultural structure',
    'HldnPK2': 'agricultural structure',
    'LSU': 'livestock pressure',
    'LSUdensity': 'livestock pressure',
    'BOVINE': 'livestock pressure',
    'PIGS': 'livestock pressure',
    'SHEEP': 'livestock pressure',
    'GOATS': 'livestock pressure',
    'POULTRY': 'livestock pressure',
    'UAA_IB': 'surface water quality', 
    'IrrShare': 'surface water quality'
 }

# global mapping of parameter codes to descriptions and units
GLOBAL_MAPPING = {
    'UAA': 'Area of land actually used for agricultural purposes',
    'ARA': 'Area of arable land',
    'AraShare': 'Share of arable land in the total agricultural area',
    'PECR': 'Area of permanent crops (e.g., orchards, plantations)',
    'PecrShare': 'Percentage of permanent crops in the UAA',
    'J0000T': 'Area of permanent grassland (meadows and pastures)',
    'GrassShare': 'Share of meadows and pastures in UAA',
    'Q0000T': 'Area of fallow land',
    'FllwShr': 'Share of fallow land in the UAA',
    'UAAXK00': 'Area of farmland managed using organic methods',
    'OrgShar': 'Percentage share of organic farming in total UAA',
    'HOLDING': 'Number of farms',
    'UAA': 'Total utilised agricultural area',
    'SO_EURO': 'Standard agricultural output expressed in euros',
    'HldnPK2': 'Density of farms',
    'LSU': 'Number of livestock units',
    'LSUdensity': 'Livestock density per hectare of agricultural land',
    'BOVINE': 'Number of head of stock',
    'PIGS': 'Number of pigs',
    'SHEEP': 'Number of sheep',
    'GOATS': 'Number of goats',
    'POULTRY': 'Number of poultry',
    'UAA_IB': 'Area of irrigable farmland', 
    'IrrShare': 'The share of irrigated land in the total area of agricultural land'
 }