# list of parameters in the parameter column
PARAMETER_VALUES = [
    'Soil Granularity: 1.0-0.1 mm [%]',
    'Soil Granularity: 0.1-0.02 mm [%]',
    'Soil Granularity: < 0.02 mm [%]',
    'Soil Granularity: 2.0-0.05 mm [%]',
    'Soil Granularity: 0.05-0.002 mm [%]',
    'Soil Granularity: < 0.002 mm [%]',
    'Soil pH H2O [pH]',
    'Soil pH KCl [pH]',
    'Soil CaCo3 [%]',
    'Humus [%]',
    'Soil Organic Carbon [%]',
    'Soil Total Nitrogen [%]',
    'Soil C/N [-]',
    'Soil Hh [cmol(+)*kg-1]',
    'Soil Hw [cmol(+)*kg-1]',
    'Soil Al [cmol(+)*kg-1]',
    'Soil Ca2+ [cmol(+)*kg-1]',
    'Soil Mg2+ [cmol(+)*kg-1]',
    'Soil Na+ [cmol(+)*kg-1]',
    'Soil K+ [cmol(+)*kg-1]',
    'Soil S [cmol(+)*kg-1]',
    'Soil T [cmol(+)*kg-1]',
    'Soil V [%]',
    'Soil Available Ammonium Nitrogen [NNH4 mg*kg-1]',
    'Soil Available Potassium [mg K2O*100g-1]',
    'Soil Available Magnesium [mg Mg*100g-1]',
    'Soil Available Sulphur [mg S-SO4*100g-1]',
    'Soil Available Ammonium Nitrogen [NNH4 mg*kg-1]',
    'Soil Available Nitrate Nitrogen [NNO3 mg*kg-1]',
    'Soil P [%]',
    'Soil Ca [%]',
    'Soil Mg [%]',
    'Soil K [%]',
    'Soil Na [%]',
    'Soil S [%]',
    'Soil Al [%]',
    'Soil Fe [%]',
    'Soil Mn [mg*kg-1]',
    'Soil Cd [mg*kg-1]',
    'Soil Cu [mg*kg-1]',
    'Soil Cr [mg*kg-1]',
    'Soil Ni [mg*kg-1]',
    'Soil Pb [mg*kg-1]',
    'Soil Zn [mg*kg-1]',
    'Soil Co [mg*kg-1]',
    'Soil V [mg*kg-1]',
    'Soil Li [mg*kg-1]',
    'Soil Be [mg*kg-1]',
    'Soil Ba [mg*kg-1]',
    'Soil Sr [mg*kg-1]',
    'Soil La [mg*kg-1]',
    'Soil Hg [mg*kg-1]',
    'Soil As [mg*kg-1]',
    'Soil PAH Sum 13 [µg*kg-1]',
    'Soil Naphthalene [µg*kg-1]',
    'Soil Phenanthrene [µg*kg-1]',
    'Soil Anthracene [µg*kg-1]',
    'Soil Fluoranthene [µg*kg-1]',
    'Soil Chrysene [µg*kg-1]',
    'Soil Benzo(a)Anthracene [µg*kg-1]',
    'Soil Benzo(a)Pyrene [µg*kg-1]',
    'Soil Benzo(a)Fluoranthene [µg*kg-1]',
    'Soil Benzo(ghi)Perylene [µg*kg-1]',
    'Soil Fluorene [µg*kg-1]',
    'Soil Pyrene [µg*kg-1]',
    'Soil Benzo(b)Fluoranthene [µg*kg-1]',
    'Soil Benzo(k)Fluoranthene [µg*kg-1]',
    'Soil Dibenzo(a,h)Anthracene [µg*kg-1]',
    'Soil Indeno(1,2,3-cd)Pyrene [µg*kg-1]',
    'Soil Organochlorine Pesticides DDT/DDE/DDD [mg*kg-1]',
    'Soil Organochlorine Pesticides Aldrin [mg*kg-1]',
    'Soil Organochlorine Pesticides Dieldrin [mg*kg-1]',
    'Soil Organochlorine Pesticides Endrin [mg*kg-1]',
    'Soil Organochlorine Pesticides Alfa-HCH [mg*kg-1]',
    'Soil Organochlorine Pesticides Beta-HCH [mg*kg-1]',
    'Soil Organochlorine Pesticides Gamma-HCH [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Carbaryl [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Carbofuran [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Maneb [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Atrazin [mg*kg-1]',
    'Soil Radioactivity [Bq*kg-1]',
    'Soil Electrical Conductivity [mS*m-1]',
    'Soil Salinity [mg KCl*100g-1]'
]


PARAMETER_SELECTION = [
    'Soil Granularity: 1.0-0.1 mm [%]',
    'Soil Granularity: 0.1-0.02 mm [%]',
    'Soil Granularity: < 0.02 mm [%]',
    'Soil Granularity: 2.0-0.05 mm [%]',
    'Soil Granularity: 0.05-0.002 mm [%]',
    'Soil Granularity: < 0.002 mm [%]',
    'Soil pH H2O [pH]',
    'Soil pH KCl [pH]',
    'Soil CaCo3 [%]',
    'Humus [%]',
    'Soil Organic Carbon [%]',
    'Soil Total Nitrogen [%]',
    'Soil C/N [-]',
    'Soil Hh [cmol(+)*kg-1]',
    'Soil Hw [cmol(+)*kg-1]',
    'Soil Al [cmol(+)*kg-1]',
    'Soil Ca2+ [cmol(+)*kg-1]',
    'Soil Mg2+ [cmol(+)*kg-1]',
    'Soil Na+ [cmol(+)*kg-1]',
    'Soil K+ [cmol(+)*kg-1]',
    'Soil S [cmol(+)*kg-1]',
    'Soil T [cmol(+)*kg-1]',
    'Soil V [%]',
    'Soil Available Ammonium Nitrogen [NNH4 mg*kg-1]',
    'Soil Available Potassium [mg K2O*100g-1]',
    'Soil Available Magnesium [mg Mg*100g-1]',
    'Soil Available Sulphur [mg S-SO4*100g-1]',
    'Soil Available Ammonium Nitrogen [NNH4 mg*kg-1]',
    'Soil Available Nitrate Nitrogen [NNO3 mg*kg-1]',
    'Soil P [%]',
    'Soil Ca [%]',
    'Soil Mg [%]',
    'Soil K [%]',
    'Soil Na [%]',
    'Soil S [%]',
    'Soil Al [%]',
    'Soil Fe [%]',
    'Soil Mn [mg*kg-1]',
    'Soil Cd [mg*kg-1]',
    'Soil Cu [mg*kg-1]',
    'Soil Cr [mg*kg-1]',
    'Soil Ni [mg*kg-1]',
    'Soil Pb [mg*kg-1]',
    'Soil Zn [mg*kg-1]',
    'Soil Co [mg*kg-1]',
    'Soil V [mg*kg-1]',
    'Soil Li [mg*kg-1]',
    'Soil Be [mg*kg-1]',
    'Soil Ba [mg*kg-1]',
    'Soil Sr [mg*kg-1]',
    'Soil La [mg*kg-1]',
    'Soil Hg [mg*kg-1]',
    'Soil As [mg*kg-1]',
    'Soil PAH Sum 13 [µg*kg-1]',
    'Soil Naphthalene [µg*kg-1]',
    'Soil Phenanthrene [µg*kg-1]',
    'Soil Anthracene [µg*kg-1]',
    'Soil Fluoranthene [µg*kg-1]',
    'Soil Chrysene [µg*kg-1]',
    'Soil Benzo(a)Anthracene [µg*kg-1]',
    'Soil Benzo(a)Pyrene [µg*kg-1]',
    'Soil Benzo(a)Fluoranthene [µg*kg-1]',
    'Soil Benzo(ghi)Perylene [µg*kg-1]',
    'Soil Fluorene [µg*kg-1]',
    'Soil Pyrene [µg*kg-1]',
    'Soil Benzo(b)Fluoranthene [µg*kg-1]',
    'Soil Benzo(k)Fluoranthene [µg*kg-1]',
    'Soil Dibenzo(a,h)Anthracene [µg*kg-1]',
    'Soil Indeno(1,2,3-cd)Pyrene [µg*kg-1]',
    'Soil Organochlorine Pesticides DDT/DDE/DDD [mg*kg-1]',
    'Soil Organochlorine Pesticides Aldrin [mg*kg-1]',
    'Soil Organochlorine Pesticides Dieldrin [mg*kg-1]',
    'Soil Organochlorine Pesticides Endrin [mg*kg-1]',
    'Soil Organochlorine Pesticides Alfa-HCH [mg*kg-1]',
    'Soil Organochlorine Pesticides Beta-HCH [mg*kg-1]',
    'Soil Organochlorine Pesticides Gamma-HCH [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Carbaryl [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Carbofuran [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Maneb [mg*kg-1]',
    'Soil Pesticides Non Chlorinated Compounds Atrazin [mg*kg-1]',
    'Soil Radioactivity [Bq*kg-1]',
    'Soil Electrical Conductivity [mS*m-1]',
    'Soil Salinity [mg KCl*100g-1]'
]

DATA_ALIASES = {
    'Soil Granularity: 1.0-0.1 mm [%]': 'soil',
    'Soil Granularity: 0.1-0.02 mm [%]': 'soil',
    'Soil Granularity: < 0.02 mm [%]': 'soil',
    'Soil Granularity: 2.0-0.05 mm [%]': 'soil',
    'Soil Granularity: 0.05-0.002 mm [%]': 'soil',
    'Soil Granularity: < 0.002 mm [%]': 'soil',
    'Soil pH H2O [pH]': 'soil',
    'Soil pH KCl [pH]': 'soil',
    'Soil CaCo3 [%]': 'soil',
    'Humus [%]': 'soil',
    'Soil Organic Carbon [%]': 'soil',
    'Soil Total Nitrogen [%]': 'soil',
    'Soil C/N [-]': 'soil',
    'Soil Hh [cmol(+)*kg-1]': 'soil',
    'Soil Hw [cmol(+)*kg-1]': 'soil',
    'Soil Al [cmol(+)*kg-1]': 'soil',
    'Soil Ca2+ [cmol(+)*kg-1]': 'soil',
    'Soil Mg2+ [cmol(+)*kg-1]': 'soil',
    'Soil Na+ [cmol(+)*kg-1]': 'soil',
    'Soil K+ [cmol(+)*kg-1]': 'soil',
    'Soil S [cmol(+)*kg-1]': 'soil',
    'Soil T [cmol(+)*kg-1]': 'soil',
    'Soil V [%]': 'soil',
    'Soil Available Ammonium Nitrogen [NNH4 mg*kg-1]': 'soil',
    'Soil Available Potassium [mg K2O*100g-1]': 'soil',
    'Soil Available Magnesium [mg Mg*100g-1]': 'soil',
    'Soil Available Sulphur [mg S-SO4*100g-1]': 'soil',
    'Soil Available Ammonium Nitrogen [NNH4 mg*kg-1]': 'soil',
    'Soil Available Nitrate Nitrogen [NNO3 mg*kg-1]': 'soil',
    'Soil P [%]': 'soil',
    'Soil Ca [%]': 'soil',
    'Soil Mg [%]': 'soil',
    'Soil K [%]': 'soil',
    'Soil Na [%]': 'soil',
    'Soil S [%]': 'soil',
    'Soil Al [%]': 'soil',
    'Soil Fe [%]': 'soil',
    'Soil Mn [mg*kg-1]': 'soil',
    'Soil Cd [mg*kg-1]': 'soil',
    'Soil Cu [mg*kg-1]': 'soil',
    'Soil Cr [mg*kg-1]': 'soil',
    'Soil Ni [mg*kg-1]': 'soil',
    'Soil Pb [mg*kg-1]': 'soil',
    'Soil Zn [mg*kg-1]': 'soil',
    'Soil Co [mg*kg-1]': 'soil',
    'Soil V [mg*kg-1]': 'soil',
    'Soil Li [mg*kg-1]': 'soil',
    'Soil Be [mg*kg-1]': 'soil',
    'Soil Ba [mg*kg-1]': 'soil',
    'Soil Sr [mg*kg-1]': 'soil',
    'Soil La [mg*kg-1]': 'soil',
    'Soil Hg [mg*kg-1]': 'soil',
    'Soil As [mg*kg-1]': 'soil',
    'Soil PAH Sum 13 [µg*kg-1]': 'soil',
    'Soil Naphthalene [µg*kg-1]': 'soil',
    'Soil Phenanthrene [µg*kg-1]': 'soil',
    'Soil Anthracene [µg*kg-1]': 'soil',
    'Soil Fluoranthene [µg*kg-1]': 'soil',
    'Soil Chrysene [µg*kg-1]': 'soil',
    'Soil Benzo(a)Anthracene [µg*kg-1]': 'soil',
    'Soil Benzo(a)Pyrene [µg*kg-1]': 'soil',
    'Soil Benzo(a)Fluoranthene [µg*kg-1]': 'soil',
    'Soil Benzo(ghi)Perylene [µg*kg-1]': 'soil',
    'Soil Fluorene [µg*kg-1]': 'soil',
    'Soil Pyrene [µg*kg-1]': 'soil',
    'Soil Benzo(b)Fluoranthene [µg*kg-1]': 'soil',
    'Soil Benzo(k)Fluoranthene [µg*kg-1]': 'soil',
    'Soil Dibenzo(a,h)Anthracene [µg*kg-1]': 'soil',
    'Soil Indeno(1,2,3-cd)Pyrene [µg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides DDT/DDE/DDD [mg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides Aldrin [mg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides Dieldrin [mg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides Endrin [mg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides Alfa-HCH [mg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides Beta-HCH [mg*kg-1]': 'soil',
    'Soil Organochlorine Pesticides Gamma-HCH [mg*kg-1]': 'soil',
    'Soil Pesticides Non Chlorinated Compounds Carbaryl [mg*kg-1]': 'soil',
    'Soil Pesticides Non Chlorinated Compounds Carbofuran [mg*kg-1]': 'soil',
    'Soil Pesticides Non Chlorinated Compounds Maneb [mg*kg-1]': 'soil',
    'Soil Pesticides Non Chlorinated Compounds Atrazin [mg*kg-1]': 'soil',
    'Soil Radioactivity [Bq*kg-1]': 'soil',
    'Soil Electrical Conductivity [mS*m-1]': 'soil',
    'Soil Salinity [mg KCl*100g-1]': 'soil'
}
