CODES = {
    # English Name: [Parameter Codes]
    'Phosphorus': ['1350'],  # Phosphates
    'Nitrate': ['1340'],  # Nitrates
    'Arsenic': ['1369'],
    'Cadmium': ['1388'],
    'Zinc': ['1383'],
    'Lead': ['1382'],
    'Salinity': ['1303'],  # Electrical Conductivity
    'Calcium': ['1374'],
    'Potassium': ['1367'],
    'Sodium': ['1375'],
    'Magnesium': ['1372'],
    'pH': ['1302'],
    'Chlorine': ['1337'],
    'Pesticides': ['6276'],
    'Perfluorodecane sulfonic acid (PFDS)': ['6550'],
    'Perfluoro-n-hexanoic acid (PFHxA)': ['5978'],
    'Perfluorodecanoic acid (PFDA)': ['6509'],
    'Perfluorododecanoic acid (PFDoA)': ['6507'],
    'Perfluoropentane sulfonic acid (PFPeS)': ['8738'],
    'Perfluorooctanoic acid (PFOA)': ['5347'],
    'Perfluorododecane sulfonic acid (PFDoDS)': ['8741'],
    'Perfluoro-n-nonanoic acid (PFNA)': ['6508'],
    'Perfluorononane sulfonic acid (PFNS)': ['8739'],
    'Perfluoroundecane sulfonic acid (PFUnDS)': ['8740'],
    'Perfluoro-n-butanoic acid (PFBA)': ['5980'],
    'Perfluorotridecanoic acid (PFTriDA)': ['6549'],
    'Perfluorooctane sulfonate (PFOS)': [['6561'], ['6560']],
    'Perfluorohexane sulfonic acid (PFHxS)': ['6830'],
    'Perfluoro-n-pentanoic acid (PFPeA)': ['5979'],
    'Perfluoro-n-heptanoic acid (PFHpA)': ['5977'],
    'Perfluorotridecane sulfonic acid (PFTriDS)': ['8742'],
    'Perfluoroheptane sulfonic acid (PFHpS)': ['6542'],
    'Perfluorobutane sulfonic acid (PFBS)': ['6025'],
    'Perfluoro-n-undecanoic acid (PFUnA)': ['6510'],
    'Pentacosafluorotridecanoic acid (PFTriDA)': ['6549']
}

COLUMNS = ['lat', 'lon', 'Timestamp',
           'Acide pentacosafluorotridecanoique',
           'Acide perfluoro-dodecanoïque',
           'Acide perfluoro-n-butanoïque',
           'Acide perfluoro-n-heptanoïque',
           'Acide perfluoro-n-nonanoïque',
           'Acide perfluoro-n-pentanoïque',
           'Acide perfluoro-n-undecanoïque',
           'Acide perfluoro-octanoïque',
           'Acide perfluorodecane sulfonique',
           'Acide perfluorododecane sulfonique',
           'Acide perfluoroheptane sulfonique',
           'Acide perfluorononane sulfonique',
           'Acide perfluoropentane sulfonique',
           'Acide perfluorotridecane sulfonique',
           'Acide perfluoroundecane sulfonique',
           'Acide sulfonique de perfluorobutane',
           'Acide sulfonique de perfluorooctane',
           'Arsenic',
           'Cadmium',
           'Calcium',
           'Chlorures',
           'Conductivité à 25°C',
           'Magnésium',
           'Nitrates',
           'Perfluorohexanesulfonic acid',
           'Phosphore total',
           'Plomb',
           'Potassium',
           'Potentiel en Hydrogène (pH)',
           'Sodium',
           'Somme des pesticides totaux',
           'Sulfonate de perfluorooctane',
           'Zinc']

MAPPING = {
    'Acide pentacosafluorotridecanoique': 'Pentacosafluorotridecanoic acid (µg/L)',
    'Acide perfluoro-dodecanoïque': 'Perfluorododecanoic acid (µg/L)',
    'Acide perfluoro-n-butanoïque': 'Perfluorobutanoic acid (µg/L)',
    'Acide perfluoro-n-heptanoïque': 'Perfluoroheptanoic acid (µg/L)',
    'Acide perfluoro-n-nonanoïque': 'Perfluorononanoic acid (µg/L)',
    'Acide perfluoro-n-pentanoïque': 'Perfluoropentanoic acid (µg/L)',
    'Acide perfluoro-n-undecanoïque': 'Perfluoroundecanoic acid (µg/L)',
    'Acide perfluoro-octanoïque': 'Perfluorooctanoic acid (µg/L)',
    'Acide perfluorodecane sulfonique': 'Perfluorodecane sulfonic acid (µg/L)',
    'Acide perfluorododecane sulfonique': 'Perfluorododecane sulfonic acid (µg/L)',
    'Acide perfluoroheptane sulfonique': 'Perfluoroheptane sulfonic acid (µg/L)',
    'Acide perfluorononane sulfonique': 'Perfluorononane sulfonic acid (µg/L)',
    'Acide perfluoropentane sulfonique': 'Perfluoropentane sulfonic acid (µg/L)',
    'Acide perfluorotridecane sulfonique': 'Perfluorotridecane sulfonic acid (µg/L)',
    'Acide perfluoroundecane sulfonique': 'Perfluoroundecane sulfonic acid (µg/L)',
    'Acide sulfonique de perfluorobutane': 'Perfluorobutane sulfonic acid (µg/L)',
    'Acide sulfonique de perfluorooctane': 'Perfluorooctane sulfonic acid (mµg/L)',
    'Arsenic': 'Arsenic (µg/L)',
    'Cadmium': 'Cadmium (µg/L)',
    'Calcium': 'Calcium (mg/L)',
    'Chlorures': 'Chlorides (mg/L)',
    'Conductivité à 25°C': 'Conductivity at 25°C (µS/cm)',
    'Magnésium': 'Magnesium (mg/L)',
    'Nitrates': 'Nitrates (mg/L)',
    'Perfluorohexanesulfonic acid': 'Perfluorohexanesulfonic acid (µg/L)',
    'Phosphore total': 'Total Phosphorus (mg/L)',
    'Plomb': 'Lead (µg/L)',
    'Potassium': 'Potassium (mg/L)',
    'Potentiel en Hydrogène (pH)': 'Hydrogen Potential (pH)',
    'Sodium': 'Sodium (mg/L)',
    'Somme des pesticides totaux': 'Total Pesticides (µg/L)',
    'Sulfonate de perfluorooctane': 'Perfluorooctane sulfonate (µg/L)',
    'Zinc': 'Zinc (µg/L)'
}

PARAMETERS_MAPPING = {
    'phosphorus': CODES['Phosphorus'],
    'nitrate': CODES['Nitrate'],
    'heavy metals': [CODES['Arsenic'], CODES['Cadmium'], CODES['Zinc'], CODES['Lead']],
    'salinity': CODES['Salinity'],
    'calcium': CODES['Calcium'],
    'potassium': CODES['Potassium'],
    'sodium': CODES['Sodium'],
    'magnesium': CODES['Magnesium'],
    'ph': CODES['pH'],
    'chlorine': CODES['Chlorine'],
    'pfas': [
        CODES['Perfluorooctane sulfonate (PFOS)'],
        CODES['Perfluoro-n-hexanoic acid (PFHxA)'],
        CODES['Perfluoro-n-nonanoic acid (PFNA)'],
        CODES['Perfluorohexane sulfonic acid (PFHxS)'],
    ],
    'pesticides': CODES['Pesticides'],
    'water quality': [x[0] for x in CODES.values()]
}