new_headers = ['point_id',
                  'lat',
                  'lon',
                  'date',
                  'nitrogen',
                  'BOD5',
                  'suspended_solids',
                  'oxygen',
                  'sulfate',
                  'chloride',
                  'ammonium',
                  'nitrate',
                  'nitrite',
                  'phosphate',
                  'SPAR',
                  'permanganate',
                  'COD',
                  'phytoplankton',
                  'altrazine',
                  'simazine']

DATA_ALIASES = {'nitrogen': 'sw quality',
                'BOD5': 'sw quality',
                'suspended_solids': 'sw quality',
                'oxygen': 'sw quality',
                'sulfate': 'sw quality',
                'chloride': 'sw quality',
                'ammonium': 'sw quality',
                'nitrate': 'sw quality',
                'nitrite': 'sw quality',
                'phosphate': 'sw quality',
                'SPAR': 'sw quality',
                'permanganate': 'sw quality',
                'COD': 'sw quality',
                'phytoplankton': 'sw quality',
                'altrazine': 'sw quality',
                'simazine': 'sw quality'
                }
